export type City={slug:string;name:string;region:string;intro:string;about:string;places:string[];routes:string[];image:string;gallery:string[]};
const img=(id:string)=>`https://images.unsplash.com/${id}?auto=format&fit=crop&w=1200&q=82`;
export const cities:City[]=[
['bhavnath','Bhavnath','Junagadh','Gateway to Girnar and spiritual Junagadh.','Bhavnath Taleti is the natural starting point for Girnar visits, temple trips and Junagadh sightseeing.','Bhavnath Mahadev Temple','Girnar','Damodar Kund','Uparkot Fort','Sakkarbaug Zoo','Junagadh Railway Station'],
['junagadh','Junagadh','Saurashtra','Historic city at the foot of Girnar.','Junagadh combines forts, temples, wildlife access and Girnar pilgrimage routes, making it a strong base for Saurashtra trips.','Girnar','Uparkot Fort','Mahabat Maqbara','Sakkarbaug Zoo','Damodar Kund','Ashoka Rock Edicts'],
['somnath','Somnath','Saurashtra Coast','A spiritual coastal destination on the Arabian Sea.','Somnath is known for the Somnath Temple and nearby coastal and pilgrimage attractions.','Somnath Temple','Triveni Sangam','Bhalka Tirth','Gita Mandir','Somnath Beach','Prabhas Patan'],
['dwarka','Dwarka','Devbhumi Dwarka','A major pilgrimage destination on the western coast.','Dwarka is known for Dwarkadhish Temple, Gomti Ghat and coastal pilgrimage circuits.','Dwarkadhish Temple','Gomti Ghat','Rukmini Devi Temple','Beyt Dwarka','Nageshwar Jyotirlinga','Shivrajpur Beach'],
['rajkot','Rajkot','Saurashtra','A major commercial and travel hub in Saurashtra.','Rajkot is a convenient base for business travel, airport transfers and onward trips across Gujarat.','Kaba Gandhi No Delo','Rotary Midtown Dolls Museum','Watson Museum','Aji Dam','Pradhyuman Zoological Park'],
['ahmedabad','Ahmedabad','Central Gujarat','Gujarat’s major business and urban travel hub.','Ahmedabad offers heritage, food, business and airport connectivity, making it a key taxi destination.','Sabarmati Ashram','Adalaj Stepwell','Kankaria Lake','Sidi Saiyyed Mosque','Science City','Sabarmati Riverfront'],
['vadodara','Vadodara','Central Gujarat','A cultural city known for palaces, museums and art.','Vadodara is popular for heritage sightseeing, business travel and Statue of Unity connections.','Laxmi Vilas Palace','Sayaji Garden','Baroda Museum','EME Temple','Kirti Mandir'],
['jamnagar','Jamnagar','Saurashtra Coast','Coastal city and gateway to marine and wildlife attractions.','Jamnagar is useful for airport transfers, business trips and journeys toward Dwarka and the coast.','Lakhota Lake','Lakhota Palace','Bala Hanuman Temple','Marine National Park','Khijadiya Bird Sanctuary'],
['porbandar','Porbandar','Saurashtra Coast','Coastal heritage city associated with Mahatma Gandhi.','Porbandar combines coastal travel with heritage and nearby pilgrimage routes.','Kirti Mandir','Sudama Temple','Chowpatty Beach','Porbandar Bird Sanctuary','Huzoor Palace'],
['bhavnagar','Bhavnagar','Saurashtra','A historic port city and gateway to pilgrimage and wildlife circuits.','Bhavnagar connects visitors to Palitana, Velavadar and coastal Gujarat.','Takhteshwar Temple','Victoria Park','Gaurishankar Lake','Nilambag Palace','Palitana Jain Temples'],
['gandhinagar','Gandhinagar','Central Gujarat','Planned capital city with major attractions nearby.','Gandhinagar is convenient for business travel and visits to Akshardham, Adalaj and Ahmedabad.','Akshardham','Adalaj Stepwell','Indroda Nature Park','Dandi Kutir','Children’s Park'],
['salangpur','Salangpur','Botad District','A famous pilgrimage stop in Gujarat.','Salangpur is best known for the Hanuman temple and is commonly combined with nearby pilgrimage routes.','Kashtabhanjan Hanuman Temple','Salangpur Hanumanji Temple','Botad','Gadhada','Ghela Somnath'],
['palitana','Palitana','Bhavnagar District','A renowned Jain pilgrimage destination on Shatrunjaya Hill.','Palitana is famous for its hilltop temple complex and pilgrimage experience.','Shatrunjaya Hill','Adishwar Temple','Palitana Jain Temples','Taleti','Gheti Pagoda'],
['amreli','Amreli','Saurashtra','A Saurashtra city connecting regional towns and wildlife routes.','Amreli is useful as a regional taxi base for Junagadh, Gir and surrounding towns.','Amreli District Museum','Chanchai Waterfall','Khijadiya','Gir region','Dhari'],
['botad','Botad','Saurashtra','A regional city connecting major pilgrimage routes.','Botad is well placed for Salangpur, Gadhada and Saurashtra road journeys.','Salangpur','Gadhada','Gopinath Mahadev','Lothal route','Ghela Somnath'],
['gandhidham','Gandhidham','Kutch','A major Kutch commercial and logistics hub.','Gandhidham is a useful base for Kutch travel, business trips and airport/rail connections.','Gandhidham town','Kandla Port area','Gandhi Samadhi','Adipur','Kutch routes'],
['bhuj','Bhuj','Kutch','A gateway to Kutch heritage and the Rann.','Bhuj connects travelers to palaces, museums, handicrafts and the Great Rann of Kutch.','Aina Mahal','Prag Mahal','Kutch Museum','Hamirsar Lake','Bhujodi','Great Rann of Kutch'],
['mahesana','Mahesana','North Gujarat','A North Gujarat city with heritage and regional connectivity.','Mahesana is a practical base for Modhera, Patan and North Gujarat journeys.','Modhera Sun Temple','Rani ki Vav','Thol Lake','Taranga','Bahucharaji Temple'],
['surat','Surat','South Gujarat','A major business city known for food, textiles and diamonds.','Surat offers strong business connectivity and is a gateway to South Gujarat attractions.','Dumas Beach','Sarthana Nature Park','Dutch Garden','Science Centre','Gopi Talav'],
['kevadiya','Kevadiya','Narmada District','A tourism hub around the Statue of Unity region.','Kevadiya is the base for Statue of Unity attractions, riverfront experiences and nearby nature sites.','Statue of Unity','Valley of Flowers','Glow Garden','Ekta Cruise','Cactus Garden','Jungle Safari'],
['statue-of-unity','Statue of Unity','Narmada District','India’s iconic monument and a major Gujarat tourism destination.','The Statue of Unity region offers a full-day sightseeing circuit with gardens, museums and river experiences.','Statue of Unity','Viewing Gallery','Valley of Flowers','Glow Garden','Ekta Cruise','Sardar Sarovar Dam']
].map(x=>({slug:x[0],name:x[1],region:x[2],intro:x[3],about:x[4],places:x.slice(5),routes:[],image:img('photo-1500530855697-b586d89ba3ee'),gallery:[img('photo-1516483638261-f4dbaf036963'),img('photo-1524492412937-b28074a5d7da'),img('photo-1548013146-72479768bada')]}));
const routeMap:Record<string,string[]>= {junagadh:['Junagadh → Somnath','Junagadh → Dwarka','Junagadh → Sasan Gir','Junagadh → Rajkot'],bhavnath:['Bhavnath → Somnath','Bhavnath → Dwarka','Bhavnath → Sasan Gir','Bhavnath → Ahmedabad'],ahmedabad:['Ahmedabad → Somnath','Ahmedabad → Dwarka','Ahmedabad → Statue of Unity','Ahmedabad → Rajkot'],rajkot:['Rajkot → Jamnagar','Rajkot → Dwarka','Rajkot → Junagadh','Rajkot → Ahmedabad'],somnath:['Somnath → Junagadh','Somnath → Dwarka','Somnath → Gir','Somnath → Rajkot'],dwarka:['Dwarka → Jamnagar','Dwarka → Somnath','Dwarka → Rajkot','Dwarka → Ahmedabad']};
export const cityList=cities.map(c=>c.name); for(const c of cities)c.routes=routeMap[c.slug]||[`${c.name} → Junagadh`,`${c.name} → Ahmedabad`,`${c.name} → Rajkot`,`${c.name} → Somnath`];
export function getCity(slug:string){return cities.find(c=>c.slug===slug)}
